import type { Column } from "@/components/DataTable";
import { fmtCpm, fmtInt, fmtUsd } from "@/lib/format";
import type { CommentaryRow, GrassrootRow, LongTermRow } from "@/lib/types";

export const grassrootColumns: Column<GrassrootRow>[] = [
  { key: "creator_name", header: "达人", width: 120, render: (r) => r.creator_name },
  { key: "creator_key", header: "UID", width: 120, render: (r) => r.creator_key },
  { key: "contract_types", header: "合同类型", width: 150, render: (r) => r.contract_types.join("、") || "-" },
  { key: "followers", header: "结算粉丝数", width: 100, align: "right", render: (r) => fmtInt(r.followers) },
  { key: "youtube_followers", header: "YouTube粉丝数", width: 120, align: "right", render: (r) => fmtInt(r.youtube_followers) },
  { key: "tiktok_followers", header: "TikTok粉丝数", width: 120, align: "right", render: (r) => fmtInt(r.tiktok_followers) },
  { key: "settlement_status", header: "结算状态", width: 110, render: (r) => r.settlement_status },
  { key: "rank", header: "等级", width: 70, render: (r) => r.rank },
  { key: "settlement_subtype", header: "计费类型", width: 110, render: (r) => r.settlement_subtype ?? "-" },
  { key: "contract_billable_views", header: "合同内播放量", width: 120, align: "right", render: (r) => fmtInt(r.contract_billable_views) },
  { key: "billable_views", header: "计费播放量", width: 110, align: "right", render: (r) => fmtInt(r.billable_views) },
  { key: "all_video_views", header: "全部视频播放量", width: 130, align: "right", render: (r) => fmtInt(r.all_video_views) },
  { key: "cpm_views_no_boost", header: "CPM播放量（无加成）", width: 145, align: "right", render: (r) => fmtInt(r.cpm_views_no_boost) },
  { key: "billable_post_count", header: "计费投稿数", width: 100, align: "right", render: (r) => fmtInt(r.billable_post_count) },
  { key: "short_rank_reward", header: "Short等级金额", width: 120, align: "right", render: (r) => fmtInt(r.rewards_jpy?.short_rank), exportValue: (r) => r.rewards_jpy?.short_rank },
  { key: "long_rank_reward", header: "Long+直播等级金额", width: 145, align: "right", render: (r) => fmtInt(r.rewards_jpy?.long_livestream_rank), exportValue: (r) => r.rewards_jpy?.long_livestream_rank },
  { key: "short_post_reward", header: "Short投稿奖励", width: 120, align: "right", render: (r) => fmtInt(r.rewards_jpy?.short_post), exportValue: (r) => r.rewards_jpy?.short_post },
  { key: "long_post_reward", header: "Long+直播投稿奖励", width: 145, align: "right", render: (r) => fmtInt(r.rewards_jpy?.long_livestream_post), exportValue: (r) => r.rewards_jpy?.long_livestream_post },
  { key: "creator_receivable_jpy", header: "博主应收（日元）", width: 125, align: "right", render: (r) => fmtInt(r.creator_receivable_jpy) },
  { key: "youdao_receivable_jpy", header: "有道应收（日元）", width: 125, align: "right", render: (r) => fmtInt(r.youdao_receivable_jpy) },
  { key: "creator_receivable_usd", header: "博主应收（美元）", width: 125, align: "right", render: (r) => <strong>{fmtUsd(r.creator_receivable_usd)}</strong> },
  { key: "youdao_receivable_usd", header: "有道应收（美元）", width: 125, align: "right", render: (r) => fmtUsd(r.youdao_receivable_usd) },
  { key: "cpm", header: "CPM", width: 80, align: "right", render: (r) => fmtCpm(r.cpm) },
];

export const longTermColumns: Column<LongTermRow>[] = [
  { key: "creator_name", header: "达人", width: 120, render: (r) => r.creator_name },
  { key: "creator_key", header: "UID", width: 120, render: (r) => r.creator_key },
  { key: "contract_types", header: "合同类型", width: 150, render: (r) => r.contract_types.join("、") || "-" },
  { key: "contract_start_date", header: "合同开始", width: 105, render: (r) => r.contract_start_date ?? "-" },
  { key: "contract_end_date", header: "合同截止", width: 105, render: (r) => r.contract_end_date ?? "-" },
  { key: "settlement_status", header: "结算状态", width: 110, render: (r) => r.settlement_status },
  { key: "followers", header: "粉丝数", width: 95, align: "right", render: (r) => fmtInt(r.followers) },
  { key: "rank", header: "等级", width: 70, render: (r) => r.rank },
  { key: "monthly_activity_count", header: "每月活动数", width: 100, align: "right", render: (r) => fmtInt(r.monthly_activity_count) },
  { key: "monthly_new_post_views", header: "月度投稿播放量", width: 125, align: "right", render: (r) => fmtInt(r.monthly_new_post_views) },
  { key: "cpm_views_no_boost", header: "CPM播放量（无加成）", width: 145, align: "right", render: (r) => fmtInt(r.cpm_views_no_boost) },
  { key: "youtube_post_count", header: "YouTube投稿数", width: 115, align: "right", render: (r) => fmtInt(r.youtube_post_count) },
  { key: "activity_threshold", header: "活动数门槛", width: 100, align: "right", render: (r) => fmtInt(r.activity_threshold) },
  { key: "rank_reward_jpy", header: "等级金额（日元）", width: 120, align: "right", render: (r) => fmtInt(r.rank_reward_jpy) },
  { key: "expected_cpm_jpy", header: "预计CPM（日元）", width: 120, align: "right", render: (r) => fmtInt(r.expected_cpm_jpy) },
  { key: "creator_receivable_jpy", header: "博主应收（日元）", width: 125, align: "right", render: (r) => fmtInt(r.creator_receivable_jpy) },
  { key: "youdao_receivable_jpy", header: "有道应收（日元）", width: 125, align: "right", render: (r) => fmtInt(r.youdao_receivable_jpy) },
  { key: "creator_receivable_usd", header: "博主应收（美元）", width: 125, align: "right", render: (r) => <strong>{fmtUsd(r.creator_receivable_usd)}</strong> },
  { key: "youdao_receivable_usd", header: "有道应收（美元）", width: 125, align: "right", render: (r) => fmtUsd(r.youdao_receivable_usd) },
  { key: "cpm", header: "CPM", width: 80, align: "right", render: (r) => fmtCpm(r.cpm) },
];

export const commentaryColumns: Column<CommentaryRow>[] = [
  { key: "creator_name", header: "达人", width: 120, render: (r) => r.creator_name },
  { key: "creator_key", header: "UID", width: 120, render: (r) => r.creator_key },
  { key: "contract_types", header: "合同类型", width: 150, render: (r) => r.contract_types.join("、") || "-" },
  { key: "settlement_status", header: "结算状态", width: 110, render: (r) => r.settlement_status },
  { key: "youtube_uid", header: "YouTube UID", width: 120, render: (r) => r.youtube_uid ?? "-" },
  { key: "youtube_followers", header: "YouTube粉丝数", width: 120, align: "right", render: (r) => fmtInt(r.youtube_followers) },
  { key: "tiktok_uid", header: "TikTok UID", width: 120, render: (r) => r.tiktok_uid ?? "-" },
  { key: "tiktok_followers", header: "TikTok粉丝数", width: 120, align: "right", render: (r) => fmtInt(r.tiktok_followers) },
  { key: "short_platform", header: "短视频平台", width: 105, render: (r) => r.short_platform ?? "-" },
  { key: "long_views", header: "长视频播放量", width: 115, align: "right", render: (r) => fmtInt(r.long_views) },
  { key: "long_view_rank", header: "长视频播放等级", width: 120, render: (r) => r.long_view_rank ?? "-" },
  { key: "long_follower_cap_rank", header: "长视频粉丝上限等级", width: 145, render: (r) => r.long_follower_cap_rank ?? "-" },
  { key: "long_final_rank", header: "长视频最终等级", width: 120, render: (r) => r.long_final_rank ?? "-" },
  { key: "long_reward_jpy", header: "长视频报酬（日元）", width: 135, align: "right", render: (r) => fmtInt(r.long_reward_jpy) },
  { key: "short_views", header: "短视频播放量", width: 115, align: "right", render: (r) => fmtInt(r.short_views) },
  { key: "short_view_rank", header: "短视频播放等级", width: 120, render: (r) => r.short_view_rank ?? "-" },
  { key: "short_follower_cap_rank", header: "短视频粉丝上限等级", width: 145, render: (r) => r.short_follower_cap_rank ?? "-" },
  { key: "short_final_rank", header: "短视频最终等级", width: 120, render: (r) => r.short_final_rank ?? "-" },
  { key: "short_reward_jpy", header: "短视频报酬（日元）", width: 135, align: "right", render: (r) => fmtInt(r.short_reward_jpy) },
  { key: "combined_bonus_rank", header: "并用奖金等级", width: 110, render: (r) => r.combined_bonus_rank ?? "-" },
  { key: "combined_bonus_jpy", header: "并用奖金（日元）", width: 120, align: "right", render: (r) => fmtInt(r.combined_bonus_jpy) },
  { key: "designated_theme_count", header: "指定主题件数", width: 105, align: "right", render: (r) => fmtInt(r.designated_theme_count) },
  { key: "designated_theme_reward_jpy", header: "指定主题报酬（日元）", width: 145, align: "right", render: (r) => fmtInt(r.designated_theme_reward_jpy) },
  { key: "all_paid_views", header: "全部计费播放量", width: 125, align: "right", render: (r) => fmtInt(r.all_paid_views) },
  { key: "total_jpy_tax_incl", header: "含税报酬（日元）", width: 125, align: "right", render: (r) => fmtInt(r.total_jpy_tax_incl) },
  { key: "creator_receivable_jpy", header: "博主应收（日元）", width: 125, align: "right", render: (r) => fmtInt(r.creator_receivable_jpy) },
  { key: "youdao_receivable_jpy", header: "有道应收（日元）", width: 125, align: "right", render: (r) => fmtInt(r.youdao_receivable_jpy) },
  { key: "creator_receivable_usd", header: "博主应收（美元）", width: 125, align: "right", render: (r) => <strong>{fmtUsd(r.creator_receivable_usd)}</strong> },
  { key: "youdao_receivable_usd", header: "有道应收（美元）", width: 125, align: "right", render: (r) => fmtUsd(r.youdao_receivable_usd) },
  { key: "cpm", header: "CPM", width: 80, align: "right", render: (r) => fmtCpm(r.cpm) },
];
